### ISSUE TITLE
Broken on latest gateway

### ISSUE THREAD

**Issue by freaktechnik** [flatsiedatsie/followers-addon#8]
I get the following error after installation in the logs:
```
2020-11-13 16:56:30.688 INFO   : Loading add-on: followers
2020-11-13 16:56:30.811 ERROR  : followers: Traceback (most recent call last):
2020-11-13 16:56:30.811 ERROR  : followers:   File "/home/node/.mozilla-iot/addons/followers/main.py", line 13, in <module>
2020-11-13 16:56:30.811 ERROR  : followers:     from pkg.followers import FollowersAPIHandler  # noqa
2020-11-13 16:56:30.811 ERROR  : followers:   File "/home/node/.mozilla-iot/addons/followers/pkg/followers.py", line 8, in <module>
2020-11-13 16:56:30.811 ERROR  : followers:     import requests
2020-11-13 16:56:30.811 ERROR  : followers: ModuleNotFoundError: No module named 'requests'
```

**Comment by flatsiedatsie** [comment]
Thanks.

Seems your `requests` module is missing. You can install it using this command:

`pip3 install requests`

(use the seashell addon to run this command)

I wonder why it's missing. Are you using the Raspberry Pi image, or have you created the gateway yourself?

**Comment by freaktechnik** [comment]
I'm using the docker image.

**Comment by flatsiedatsie** [comment]
I guess the docker image does not have the requests module. I wonder what @mrstegeman would recommend.

**Comment by mrstegeman** [comment]
You'll need to package it with your add-on like you do with all your other add-ons. The only Python package that's guaranteed to be available is `gateway_addon`.
